
pipeline:
  build:
    image: pymor/testing:${PY}
    #tags: ${DRONE_BRANCH/\//_}
    commands:
      - export PYTEST_MARKER="${MARKER}" DOCKER_TAG="${PY}"
      - .ci/drone/script.bash

matrix:
  PY:
    - 3.6
    - 3.7
  MARKER:
    - NUMPY
    - None
    - MPI
    - PIP_ONLY
