workspace:
    base: /src
    path: .

pipeline:
  build:
    image: pymor/testing:${PY}
    pull: true
    #tags: ${DRONE_BRANCH/\//_}
    commands:
      - export PYTEST_MARKER="${MARKER}" DOCKER_TAG="${PY}"
      - .ci/drone/script.bash
    secrets: [ pymor_codecov_token ]
  notify:
    image: drillster/drone-email
    host: mail.milk.pm
    from: drone@pymor.org
    when:
      status: [ changed, failure ]
    secrets:  [ email_username, email_password ]

matrix:
  PY:
    - 3.5
    - 3.6
    - 3.7
  MARKER:
    - NUMPY
    - None
    - MPI
    - PIP_ONLY
