
pipeline:
  build:
    image: pymor/testing:${PY}
    #tags: ${DRONE_BRANCH/\//_}
    commands:
      - export PYTEST_MARKER="NUMPY" DOCKER_TAG="${PY}"
      - .ci/travis/script.bash

matrix:
  PY:
    - 3.6
    - 3.7
