ARG CI_IMAGE_TAG

FROM zivgitlab.wwu.io/pymor/docker/pymor/jupyter_py3.8:${CI_IMAGE_TAG}
MAINTAINER rene.fritze@wwu.de

COPY . /tmp/pymor

RUN pip install /tmp/pymor[docs,ci,full] && rm -rf /tmp/pymor
RUN python -c "from pymor.basic import *"


ENTRYPOINT []
WORKDIR /pymor/notebooks
