Document: pymor-base
Title: Debian pymor-base Manual
Author: <insert document author here>
Abstract: This manual describes what pymor-base is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pymor-base/pymor-base.sgml.gz

Format: postscript
Files: /usr/share/doc/pymor-base/pymor-base.ps.gz

Format: text
Files: /usr/share/doc/pymor-base/pymor-base.text.gz

Format: HTML
Index: /usr/share/doc/pymor-base/html/index.html
Files: /usr/share/doc/pymor-base/html/*.html
