jobs:
- job: 'OSX_CI'
  pool:
    vmImage: macOS-10.13
  timeoutInMinutes: 240
  strategy:
    maxParallel: 8
    matrix:
      osx_python3.6:
        CONFIG: osx_python3.6
        UPLOAD_PACKAGES: False
      osx_python3.7:
        CONFIG: osx_python3.7
        UPLOAD_PACKAGES: False

  steps:
  - script: |
      echo "Removing homebrew from Azure to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew
    displayName: Remove homebrew

  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH

  - bash: |
      set -x -e
      conda config --add channels conda-forge
      conda config --set always_yes yes --set changeps1 no
      conda create --yes --name pymorEnv
      source activate activate pymorEnv
      conda install --only-deps pymor
      # these ones are not in the 0.5.1 conda build yet
      conda install pyevtk gmsh
      # these are buildtime, not a runtime,  deps for our conda package
      conda install cython pytest-cov pytest
      # install anythin which might a niew dependency with pip
      pip install -r requirements-optional.txt
      pip install -r requirements.txt
      pip install pytest-azurepipelines
    displayName: Configure conda and conda-build

  - script: |
      set -ex
      source activate pymorEnv
      conda list
      export PYTHONPATH=${PWD}/src:${PYTHONPATH}
      python setup.py build_ext -i
      py.test -r sxX -k "demos"
    displayName: py.test
