jobs:
- job: 'OSX_CI'
  pool:
    vmImage: macOS-10.13
  timeoutInMinutes: 240
  strategy:
    maxParallel: 8
    matrix:
      osx_python3.6:
        CONFIG: osx_python3.6
        UPLOAD_PACKAGES: False
      osx_python3.7:
        CONFIG: osx_python3.7
        UPLOAD_PACKAGES: False

  steps:
  # TODO: Fast finish on azure pipelines?
  - script: |
      echo "Fast Finish"


  - script: |
      echo "Removing homebrew from Azure to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew
    displayName: Remove homebrew

  - script: |
      echo "Installing Miniconda"
      set -x -e
      curl -o $(Build.StagingDirectory)/miniconda.sh https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
      chmod +x $(Build.StagingDirectory)/miniconda.sh
      $(Build.StagingDirectory)/miniconda.sh -b -p $(Build.StagingDirectory)/miniconda
      export PATH=$(Build.StagingDirectory)/miniconda/bin:$PATH
      echo "Setting up Conda environment"
    displayName: 'Install miniconda'

  - script: |
      export PATH=$(Build.StagingDirectory)/miniconda/bin:$PATH
      set -x -e
      conda install -n base -c conda-forge --quiet --yes conda-forge-ci-setup=2 conda-build
    displayName: 'Add conda-forge-ci-setup=2'

  - script: |
      set -x -e
      export PATH=$(Build.StagingDirectory)/miniconda/bin:$PATH
      echo "Configuring conda."

      conda config --add channels conda-forge
      conda config --set always_yes yes --set changeps1 no
      conda create pymorEnv
      conda activate pymorEnv
      conda install --only-deps pymor
      # these ones are not in the 0.5.1 conda build yet
      conda install pyevtk gmsh
      # these are buildtime, not a runtime,  deps for our conda package
      conda install cython pytest-cov pytest
    env: {
      OSX_FORCE_SDK_DOWNLOAD: "1"
    }
    displayName: Configure conda and conda-build

  - script: |
      set -ex
      export PATH=$(Build.StagingDirectory)/miniconda/bin:$PATH
      conda activate pymorEnv
      conda list
      export PYTHONPATH=${PWD}/src:${PYTHONPATH}
      python setup.py build_ext -i
      py.test -r sxX -k "demos"
