#!/usr/bin/env python
# -*- coding: utf-8 -*-
# This file is part of the pyMOR project (http://www.pymor.org).
# Copyright Holders: Felix Albrecht, Rene Milk, Stephan Rave
# License: BSD 2-Clause License (http://opensource.org/licenses/BSD-2-Clause)

'''Launcher script for all available pyMOR demos. 

Usage:
  pymor-demo.py ( (--help | --list )  | DEMO_NAME [DEMO_OPTIONS]... ) 


Arguments:
  DEMO_NAME     name of the demo you want to run. Use '-l' to list available demos.

  DEMO_OPTIONS  Most of pyMOR's demos require their own arguments, pass them here.

  
Options:
  -h, --help                  Show this message.

  -l, --list                  List available demo names.
'''

from __future__ import absolute_import, division, print_function

import pkgutil
import pprint
import pymordemos
from docopt import docopt
import sys
import runpy 


if __name__ == '__main__':          
    modules = []
    for _, module_name, _ in pkgutil.walk_packages(pymordemos.__path__, pymordemos.__name__ + '.'):
        try:
            foo = __import__(module_name, level=0)
            modules.append(module_name)
        except (TypeError, ImportError):
            pass

    args = docopt(__doc__)

    def print_available():
        print('Available pyMOR demo names:')
        pprint.pprint([m[len('pymordemos.'):] for m in modules])
    
    if args['--list']:
        print_available()
        sys.exit(0)
    
    mod_name = 'pymordemos.' + args['DEMO_NAME']
    if mod_name not in modules:
        print('{} is not a valid demo name'.format(args['DEMO_NAME']))
        print_available()
        sys.exit(255)
        
    # only need to remove the modname from args, rest is automatic
    del sys.argv[1]
    runpy.run_module(mod_name, init_globals=None, run_name='__main__', alter_sys=True)