---
name: Link Check
on:
  pull_request:
  merge_group:
    types:
      - checks_requested
jobs:
  markdown-link-check:
    name: Markdown
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Run linkspector
        uses: umbrelladocs/action-linkspector@v1.5.3
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          fail_level: any
